# -*- coding: utf-8 -*-
"""rod_counter_app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wdODg-rjfp8R58j_gwB4gr8BIs0BQJ6Y
"""

pip install streamlit

import streamlit as st

import cv2

import numpy as np

import tempfile
import os

st.write("Intelligent Bar Counting")

st.title("Steel bar count display")

uploaded_file = st.file_uploader("Upload an image", type=["png", "avi"])

def count_steel_rods(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    _, threshold = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(threshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    return len(contours)

def main():
    st.title("Steel Rod Counter")

uploaded_file = st.file_uploader("Upload an image", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
        image = np.array(cv2.imdecode(np.fromstring(uploaded_file.read(), np.uint8), 1))
        st.image(image, caption='Uploaded Image', use_column_width=True)

if st.button("Count Rods"):
            rod_count = count_steel_rods(image)
            st.success(f"Number of rods: {rod_count}")

if __name__ == "__main__":
    main()